export const ABI = [
    {
        "anonymous":false,
        "inputs":[
        {
            "indexed":true,
            "internalType":"address",
            "name":"owner",
            "type":"address"
        },
        {
            "indexed":true,
            "internalType":"address",
            "name":"spender",
            "type":"address"
        },
        {
            "indexed":false,
            "internalType":"uint256",
            "name":"value",
            "type":"uint256"
        }
        ],
        "name":"Approval",
        "type":"event"
    },
    {
        "anonymous":false,
        "inputs":[
           {
              "indexed":true,
              "internalType":"address",
              "name":"beneficiary",
              "type":"address"
           },
           {
              "indexed":false,
              "internalType":"uint256",
              "name":"amount",
              "type":"uint256"
           }
        ],
        "name":"Deposit",
        "type":"event"
    },
    {
        "anonymous":false,
        "inputs":[
           {
              "indexed":true,
              "internalType":"address",
              "name":"beneficiary",
              "type":"address"
           },
           {
              "indexed":false,
              "internalType":"uint256",
              "name":"amount",
              "type":"uint256"
           }
        ],
        "name":"Withdraw",
        "type":"event"
    },
    {
        "anonymous":false,
        "inputs":[
           {
              "indexed":true,
              "internalType":"address",
              "name":"user",
              "type":"address"
           },
           {
              "indexed":false,
              "internalType":"uint256",
              "name":"amount",
              "type":"uint256"
           }
        ],
        "name":"Withdrawn",
        "type":"event"
    },
    {
        "inputs":[
           {
              "internalType":"address",
              "name":"spender",
              "type":"address"
           },
           {
              "internalType":"uint256",
              "name":"amount",
              "type":"uint256"
           }
        ],
        "name":"approve",
        "outputs":[
           {
              "internalType":"bool",
              "name":"",
              "type":"bool"
           }
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
           {
              "internalType":"address",
              "name":"account",
              "type":"address"
           }
        ],
        "name":"balanceOf",
        "outputs":[
           {
              "internalType":"uint256",
              "name":"",
              "type":"uint256"
           }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
           {
              "internalType":"uint256",
              "name":"amount",
              "type":"uint256"
           }
        ],
        "name":"deposit",
        "outputs":[
           
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
           {
              "internalType":"uint256",
              "name":"amount",
              "type":"uint256"
           }
        ],
        "name":"depositAndInvest",
        "outputs":[
           
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
           {
              "internalType":"uint256",
              "name":"amount",
              "type":"uint256"
           },
           {
              "internalType":"address",
              "name":"holder",
              "type":"address"
           }
        ],
        "name":"depositFor",
        "outputs":[
           
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
           {
              "internalType":"uint256",
              "name":"numberOfShares",
              "type":"uint256"
           }
        ],
        "name":"withdraw",
        "outputs":[
           
        ],
        "stateMutability":"nonpayable",
        "type":"function"
     },
];
